# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.timeout = 7;

  fileSystems."/" =
    { device = "/dev/disk/by-label/ROOT";
      fsType = "btrfs";
      options = [ "compress=zstd:1" "noatime" "subvol=root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-label/ROOT";
      fsType = "btrfs";
      options = [ "compress-force=zstd:1" "noatime" "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/ROOT";
      fsType = "btrfs";
      options = [ "compress=zstd:1" "noatime" "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/drives/BTRFS0" =
    { device = "/dev/disk/by-label/BTRFS0";
      fsType = "btrfs";
      options = [ "compress=zstd:1" "noatime" "autodefrag" "x-systemd.device-timeout=300s" ];
    };

  fileSystems."/storage/pool" = {
     device = "/drives/BTRFS*";
     fsType = "fuse.mergerfs";
     options = [
       "minfreespace=100G"
       "category.create=mfs"
       "x-systemd.device-timeout=300s"
       "x-systemd.requires=/drives/BTRFS0" "x-systemd.after=/drives/BTRFS0"
     ];
   };

  swapDevices = [{
    device = "/swapfile";
    size = 16 * 1024; #16GB
  }];

  networking.useDHCP = lib.mkDefault true;
  hardware.graphics.enable = true;
  hardware.graphics.extraPackages = with pkgs; [ intel-media-driver ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
