# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
      luks.devices.root = {
        device = "/dev/disk/by-uuid/bd1b4c09-46f3-474d-b1a1-fde9f1ea942e";
        preLVM = true;
      };
    };
    kernelModules = [ "kvm-amd" ];
    kernelParams = [ "amdgpu.dcdebugmask=0x600" ];
    kernelPackages = pkgs.linuxPackages_6_10;
    # Enable nested virtualization
    # extraModprobeConfig = "options kvm-amd nested=1";
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/758664ba-5ad9-4f2c-8ff9-11c40d830a45";
      fsType = "btrfs";
      options = [ "subvol=root" "compress-force=zstd:3" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/758664ba-5ad9-4f2c-8ff9-11c40d830a45";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd:3" "noatime"  ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/758664ba-5ad9-4f2c-8ff9-11c40d830a45";
      fsType = "btrfs";
      options = [ "subvol=nix"  "compress-force=zstd:3" "noatime" ];
    };

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/758664ba-5ad9-4f2c-8ff9-11c40d830a45";
      fsType = "btrfs";
      options = [ "subvol=snapshots" "compress-force=zstd:3" "noatime"  ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1030-50F5";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp197s0f0u1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    graphics = {
      enable = true;
      enable32Bit = true;
    };
  };
}
