# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
      timeout = 7;
    };
    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelPackages = pkgs.linuxPackages_latest;
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/ROOT";
      fsType = "btrfs";
      options = [ "compress-force=zstd:1" "noatime" ];
    };
    "/boot" = {
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    };
    "/containers" = { # Container configs
      device = "/dev/disk/by-label/ROOT";
      fsType = "btrfs";
      options = [ "subvol=containers" "compress-force=zstd:1" "noatime" "x-systemd.device-timeout=300s" ];
    };
    "/drives/R1-BTRFS-0" = { #20tb
      device = "/dev/disk/by-label/R1-BTRFS-0";
      fsType = "btrfs";
      options = [ "compress-force=zstd:1" "noatime" "autodefrag" "x-systemd.device-timeout=300s" ];
    };
    "/drives/R1-BTRFS-1" = { #20tb
      device = "/dev/disk/by-label/R1-BTRFS-1";
      fsType = "btrfs";
      options = [ "compress-force=zstd:1" "noatime" "autodefrag" "x-systemd.device-timeout=300s" ];
    };
    "/drives/R1-BTRFS-2" = { #20tb
      device = "/dev/disk/by-label/R1-BTRFS-2";
      fsType = "btrfs";
      options = [ "compress-force=zstd:1" "noatime" "autodefrag" "x-systemd.device-timeout=300s" ];
    };
    "/drives/EXTERNAL0" = { #4TB
      device = "/dev/disk/by-uuid/78d1947e-0375-4ac3-ad0f-249803877899";
      fsType = "btrfs";
      options = [ "compress-force=zstd:1" "noatime" "autodefrag" "x-systemd.device-timeout=300s" ];
    };
    "/storage/pool" = {
      # device = "/drives/BTRFS*";
      # =NC
      device = "/drives/R1-BTRFS-0:/drives/R1-BTRFS-1:/drives/R1-BTRFS-2";
      fsType = "fuse.mergerfs";
      options = [
        "minfreespace=100G"
        "category.create=mfs"
        "x-systemd.device-timeout=300s"
        "x-systemd.requires=/drives/R1-BTRFS-0" "x-systemd.after=/drives/R1-BTRFS-0"
        "x-systemd.requires=/drives/R1-BTRFS-1" "x-systemd.after=/drives/R1-BTRFS-1"
        "x-systemd.requires=/drives/R1-BTRFS-2" "x-systemd.after=/drives/R1-BTRFS-2"
      ];
    };
  };

  swapDevices = [{
    device = "/swapfile";
    size = 64 * 1024; #64GB
  }];

  networking = {
    useDHCP = lib.mkDefault true;
    bridges."br0".interfaces = [ "enp3s0" ];
    interfaces."enp3s0".useDHCP = false;   # enp3s0 becomes the slave
    interfaces."br0".useDHCP = true;       # host's DHCP address now comes via the bridge
    firewall.trustedInterfaces = [ "br0" "wg0" ];
    networkmanager.unmanaged = [ "enp3s0" "br0" ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  services.xserver.videoDrivers = [ "nvidia" ];

  environment.systemPackages = [ pkgs.nvtopPackages.full ];
  systemd.services."limit-gpu-wattage" = {
    description = "Limit nvidia wattage";
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.bash}/bin/bash -c '/run/current-system/sw/bin/nvidia-smi -pm 1 && /run/current-system/sw/bin/nvidia-smi -pl 250'"; # Replace with your actual command
    };
    wantedBy = [ "multi-user.target" ];
  };
  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    nvidia-container-toolkit = {
      enable = true;  
    };
    nvidia = {
      powerManagement.enable = true;
      open = true;
      nvidiaSettings = true;
    };
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        intel-media-driver
      ];
    };
  };
}
